### ISSUE TITLE
Hard coded memory limit 1 GB

### ISSUE THREAD

**Issue by hannes** [tidyverse/duckplyr#174]
https://github.com/duckdblabs/duckplyr/blob/7bc1ccb925ef742cf7805c9391fec19b1233123c/R/relational-duckdb.R#L64

@krlmlr is this not a bit on the low side?

**Comment by krlmlr** [comment]
Yes, it is. We could make it configurable and talk about it.

**Comment by hadley** [comment]
I think this can now be closed?

**Comment by krlmlr** [comment]
Yes, we no longer have that. Leaving it open as a reminder to add documentation for this setting.
