### ISSUE TITLE
error in macOS: IOException - Could not remove tempfile

### ISSUE THREAD

**Issue by rafapereirabr** [tidyverse/duckplyr#203]
Hi all, thanks for such an excellent package! I'm using {duckplyr} as a dependency in my package [{censobr}](https://ipeagit.github.io/censobr/) and it works super nicely but it generates [this strange error in my cmd-checks for macOS ](https://github.com/ipeaGIT/censobr/actions/runs/9974058335/job/27560749084). The error only occurs in macOS.

> Error: Error: R CMD check found ERRORs
Execution halted
180.900 129.583 310.242 
libc++abi: terminating due to uncaught exception of type duckdb::IOException: {"exception_type":"IO","exception_message":"Could not remove file \".tmp/duckdb_temp_storage-0.tmp\": No such file or directory","errno":"2"}
>
> 1 error ✖ | 0 warnings ✔ | 0 notes ✔
> Error: Process completed with exit code 1.

The error seems to occur when GithubActions checks this function:

```
censobr::read_population(year = 2000,
                         merge_households = TRUE)
```

Internally, this is what the function is doing. It (1) opens two `.parquet` files using arrow, (2) converts them to duckdb, (3) performs a left join, and (4) converts the result back to arrow.

```
library(censobr)
library(duckplyr)
library(dplyr)

df <- censobr::read_population(year = 2000)
df_household <- censobr::read_households(year = 2000)

key_vars <- c('code_muni', 'code_state', 'abbrev_state','name_state',
              'code_region', 'name_region', 'code_weighting', 'V0300')

# drop repeated vars
all_common_vars <- names(df)[names(df) %in% names(df_household)]
vars_to_drop <- setdiff(all_common_vars, key_vars)
df_household <- dplyr::select(df_household, -all_of(vars_to_drop))

# convert to duckdb
df <- arrow::to_duckdb(df)
df_household <- arrow::to_duckdb(df_household)

# merge
df_geo <- duckplyr::left_join(df, df_household)

# back to arrow
df_geo <- arrow::to_arrow(df_geo)

```

**Comment by krlmlr** [comment]
Thanks. We might need to close the duckdb connection and shutdown duckdb (or just `gc()` ) on unload of duckplyr. Would you like to contribute a PR? Beware of dragons!

**Comment by rafapereirabr** [comment]
Hi @krlmlr , I just had a look at the code of [duckplyr::left_join()](https://github.com/duckdblabs/duckplyr/blob/main/R/left_join.R) and I couldn't find an explicit call to  `dbConnect()` so I'm not sure how to close the duckdb connection here.

Perhaps the connection to duckdb should be closed within `arrow::to_arrow()` ?

**Comment by krlmlr** [comment]
See `create_default_duckdb_connection()` .

**Comment by rafapereirabr** [comment]
Hi @krlmlr , I checked the code but I'm not really familiar with the internals of {duckplyr} so I couldn't find a way to suggest any changes here.

**Comment by krlmlr** [comment]
I see the checks in your package are now green again. Is this still an issue?

**Comment by krlmlr** [comment]
The following seems to be the only use of duckplyr in censobr:

https://github.com/ipeaGIT/censobr/blob/3a3fab5e97bc3a4baae3bb3ea5e3154e2651cebf/R/merge_household.R#L106

Effectively, this doesn't use duckplyr, but duckdb via dbplyr. This is a different code path, but gives similar performance. Would you like to use duckplyr directly?

**Comment by rafapereirabr** [comment]
indeed, the issue with macOS: IOException is now fixed! Thanks @krlmlr . 

Regarding the current use of {duckplyr} in the {censobr} package, I think I was a bit confused about how {duckplyr} works. I thought {duckplyr} would allow one to process the data without loading it to memory, but I guess I'm mistaken, right ?

**Comment by krlmlr** [comment]
It's convoluted. I'll PR to your package to explain it.

**Comment by rafapereirabr** [comment]
Thank you very much @krlmlr . I just pushed to the repo a solution performing a left join using duckdb. However, any suggestions would be very much welcomed !

**Comment by krlmlr** [comment]
With the most recent dev version, calling `duckplyr::as_duckplyr_tibble()` will enable duckplyr processing in package code. See https://duckplyr.tidyverse.org/dev/articles/developers.html#use-of-duckplyr-for-individual-data-frames (first section) for details.

Out-of-memory processing is supported, too. Stay tuned for new functions (stable API) and for documentation for processing Parquet, CSV or JSON files straight from disk or from S3.

**Comment by rafapereirabr** [comment]
Thanks @krlmlr !
