### ISSUE TITLE
Do we want to host duckplyr in tidyverse?

### ISSUE THREAD

**Issue by hadley** [tidyverse/duckplyr#206]
It doesn't make that much difference to me, but maybe it helps duckplyr feel more "official"?

`duckplyr.tidyverse.org` would definitely feel nice.

**Comment by krlmlr** [comment]
Sure! I'll prepare a PR that deals with the technical stuff so that we can minimize downtime.

**Comment by krlmlr** [comment]
Done now. 🎉
