### ISSUE TITLE
Emphasise library(duckplyr) in README

### ISSUE THREAD

**Issue by hadley** [tidyverse/duckplyr#208]
I think you should start with `library(duckplyr)` and then tell folks that if they don't want to attach it (i.e. if they're writing a package), they can instead use `as_duckplyr_tibble()`.

And most of those details should probably live in the getting started vignette, rather than in the README.

**Comment by krlmlr** [comment]
DoD:

- [ ] Rewrite README to be as short and sweet as dplyr's README
- [ ] Review
- [ ] Create "Getting started" vignette from what's now gone
- [ ] Review

**Comment by maelle** [comment]
Also add pre-requisites/resources? Probably best to have data manipulation basics before using duckplyr?

**Comment by krlmlr** [comment]
Like "If you are new to dplyr, the best place to start is the [data transformation chapter](https://r4ds.hadley.nz/data-transform) in R for Data Science." in dplyr? Sure.
