### ISSUE TITLE
Missing docs for S3 methods?

### ISSUE THREAD

**Issue by hadley** [tidyverse/duckplyr#214]
I think it would be useful to document `mutate()`, `filter()` etc methods so its obvious that duckplyr supports them. This would also be a good place to document any differences in behaviour.

**Comment by krlmlr** [comment]
DoD:

- [ ] Understand and perhaps avoid collisions that occur for `?mutate` as soon as duckplyr is loaded
- [ ] Draft for 2-3 verbs, reviewed
- [ ] Documentation for verbs similarly to `?dbplyr::mutate.tbl_lazy`
- [ ] Fallback conditions are documented
- [ ] Most important differences in behavior are documented
- [ ] Add list of verbs that are not implemented

**Comment by maelle** [comment]
Where to put the source for the docs: in a script called `mutate.R` for instance under `tools/manual`? Then the `tools/02-duckplyr_df-methods.R` would be edited to add the content of `tools/manual/mutate.R` and to automatically create part of the tags (for instance using the same title as dplyr but putting "(duckplyr)", adding a `@seealso` tag pointing to the manual page in dplyr, probably other parts of the dplyr manual page?).

**Comment by maelle** [comment]
Then I need to get to the first item in your list @krlmlr 😁

**Comment by maelle** [comment]
One process that gets me to having two manual pages loaded for `?mutate`.

![Image](https://github.com/user-attachments/assets/097e3819-7a8e-4959-af68-22c28fcb5c2f)


- in `R/duckplyr-package.R`, add an `@export` tag (before I did that, `?mutate` would be for the dplyr page, `?mutate.duckplyr_df` for the duckplyr page)

```r
#' @importFrom dplyr mutate
#' @rdname mutate
#' @export
dplyr::mutate
```

- in `R/mutate.R` have (I realize that this script should not be edited manually)

```r
# Generated by 02-duckplyr_df-methods.R
#' @rdname mutate
#' @title Create, modify, and delete columns (duckplyr)
#'
#' @description blabla
#'
#' @examples
#' library("duckplyr")
#' df <- data.frame(x = c(1, 2), row.names = c("a", "b"))
#' df <- mutate(df, y = 2)
#' df
#' @seealso [`dplyr::mutate()`]
#' @export
```

- run

**Comment by maelle** [comment]
Using something like https://github.com/eliocamp/rhelpi18n/blob/main/R/zzzz.R might be a step too far?

**Comment by maelle** [comment]
https://github.com/r-dbi/DBI/blob/50b82902541fe1f22e8eeb43f658dd69845e1bb8/man-roxygen/methods.R

https://github.com/r-dbi/DBI/blob/50b82902541fe1f22e8eeb43f658dd69845e1bb8/R/methods_as_rd.R#L1

**Comment by maelle** [comment]
`methods("mutate")` works but `methods("select")` suffers from the conflict.

**Comment by maelle** [comment]
https://github.com/tidyverse/dplyr/blob/fb25640fa1eb74746a7a74a06090045106e5d20f/R/doc-methods.R#L45

**Comment by krlmlr** [comment]
I don't follow:

``` r
options(conflicts.policy = list(warn = FALSE))
library(dplyr)

dplyr:::methods_generic("mutate")
#> # A tibble: 1 × 7
#>   generic class      package topic visible source              isS4 
#>   <chr>   <chr>      <chr>   <chr> <lgl>   <chr>               <lgl>
#> 1 mutate  data.frame dplyr   <NA>  FALSE   registered S3method FALSE
dplyr:::methods_generic("select")
#> # A tibble: 1 × 7
#>   generic class      package topic visible source              isS4 
#>   <chr>   <chr>      <chr>   <chr> <lgl>   <chr>               <lgl>
#> 1 select  data.frame dplyr   <NA>  FALSE   registered S3method FALSE

library(dbplyr)
library(dtplyr)
library(dm)

dplyr:::methods_generic("mutate")
#> # A tibble: 5 × 7
#>   generic class       package topic                    visible source      isS4 
#>   <chr>   <chr>       <chr>   <chr>                    <lgl>   <chr>       <lgl>
#> 1 mutate  data.frame  dplyr   <NA>                     FALSE   registered… FALSE
#> 2 mutate  dm          dm      <NA>                     FALSE   registered… FALSE
#> 3 mutate  dm_zoomed   dm      dplyr_table_manipulation FALSE   registered… FALSE
#> 4 mutate  dtplyr_step dtplyr  mutate.dtplyr_step       FALSE   registered… FALSE
#> 5 mutate  tbl_lazy    dbplyr  mutate.tbl_lazy          FALSE   registered… FALSE
dplyr:::methods_generic("select")
#> # A tibble: 5 × 7
#>   generic class       package topic                    visible source      isS4 
#>   <chr>   <chr>       <chr>   <chr>                    <lgl>   <chr>       <lgl>
#> 1 select  data.frame  dplyr   <NA>                     FALSE   registered… FALSE
#> 2 select  dm          dm      <NA>                     FALSE   registered… FALSE
#> 3 select  dm_zoomed   dm      dplyr_table_manipulation FALSE   registered… FALSE
#> 4 select  dtplyr_step dtplyr  select.dtplyr_step       FALSE   registered… FALSE
#> 5 select  tbl_lazy    dbplyr  select.tbl_lazy          FALSE   registered… FALSE
```

<sup>Created on 2024-11-21 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by maelle** [comment]
to find fallbacks: `rel_try()`

**Comment by maelle** [comment]
add `rdname` via automation. it'd also be better to create the `mutate-rd.R` file for instance via automation.

- title from dplyr
- sentences "This is a method for the [dplyr::select()](http://127.0.0.1:22237/help/library/dplyr/help/select?dev=select) generic. See "Fallbacks" section for differences in implementation.", then description from dplyr
- params from dplyr
- seealso
- examples from dplyr


To be done by hand anyway: adding the fallback section to the source e.g. `R/select.R`. Should not be lost by sync.

**Comment by maelle** [comment]
special family and pkgdown index section for the `"No relational implementation for` verbs? could use a template in the automatic generation.
