### ISSUE TITLE
Better parsing errors

### ISSUE THREAD

**Issue by hadley** [tidyverse/duckplyr#219]
```
> DBI::dbGetQuery(con, "SELECT count(*), date FROM SELECT CAST(time AS date), count(*) GROUP by date;")
Error:
! {"exception_type":"Parser","exception_message":"syntax error at or near \"SELECT\"","position":"27","error_subtype":"SYNTAX_ERROR"}
```

Would be nicer as:

```
Error in dbGetQuery():
* Failed to parse SQL
* syntax error at or near \"SELECT\"
```

Or similar

**Comment by krlmlr** [comment]
DoD:

- [ ] JSON from error message is parsed and translated to structured classed exceptions
- [ ] `print()` method for our exceptions

**Comment by krlmlr** [comment]
Parse JSON with duckdb, don't need jsonlite as dependency.

**Comment by krlmlr** [comment]
``` r
library(DBI)

con <- dbConnect(duckdb::duckdb())
sql <- "SELECT count(*), date FROM SELECT CAST(time AS date), count(*) GROUP by date;"
dbGetQuery(con, sql)
#> Error: {"exception_type":"Parser","exception_message":"syntax error at or near \"SELECT\"","position":"27","error_subtype":"SYNTAX_ERROR"}

e <- tryCatch(
  dbGetQuery(con, sql),
  error = identity
)
msg <- conditionMessage(e)

dbExecute(con, "LOAD json")
#> [1] 0
out <- dbGetQuery(con, "SELECT json_transform(?, json_structure(?)) AS msg", params = list(msg, msg))
as.list(out[[1]])
#> $exception_type
#> [1] "Parser"
#> 
#> $exception_message
#> [1] "syntax error at or near \"SELECT\""
#> 
#> $position
#> [1] "27"
#> 
#> $error_subtype
#> [1] "SYNTAX_ERROR"

dbDisconnect(con)
```

<sup>Created on 2024-10-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by krlmlr** [comment]
Currently on my machine:

``` r
library(DBI)

con <- dbConnect(duckdb::duckdb())
sql <- "SELECT count(*), date FROM SELECT CAST(time AS date), count(*) GROUP by date;"
dbGetQuery(con, sql)
#> Error in `dbSendQuery()` at DBI/R/dbGetQuery_DBIConnection_character.R:5:3:
#> ! syntax error at or near "SELECT"
#> ℹ exception_type: Parser
#> ℹ position: 27
#> ℹ error_subtype: SYNTAX_ERROR
rlang::last_error()
#> Error: Can't show last error because no error was recorded yet
```

<sup>Created on 2024-10-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
We'd have to do additinal gymnastics to show `dbGetQuery()` in the error message. I wonder why `last_error()` and `last_trace()` don't work, I'm calling `rlang::abort()` internally.

**Comment by krlmlr** [comment]
Oh, it's a reprex thing, it's shown in the default backtrace.

**Comment by krlmlr** [comment]
We can parse JSON, but this is really needed only for uncaught duckdb exceptions. We get much better results here with catching and adding context in the C++ glue:

``` r
library(DBI)

con <- dbConnect(duckdb::duckdb())
sql <- "SELECT count(*), date FROM SELECT CAST(time AS date), count(*) GROUP by date;"
dbGetQuery(con, sql)
#> Error in `dbSendQuery()` at DBI/R/dbGetQuery_DBIConnection_character.R:5:3:
#> ! rapi_prepare: Failed to extract statements:
#> Parser Error: syntax error at or near "SELECT"
#> LINE 1: SELECT count(*), date FROM SELECT CAST(time AS date), count(*) GRO...
#>                                    ^
```

<sup>Created on 2024-10-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

I keep the JSON parsing code, but it will only be in effect when exceptions come through unfiltered. We could use JSON everywhere, though: https://github.com/duckdb/duckdb-r/issues/519.

**Comment by krlmlr** [comment]
The JSON parsing now adds little extra value, I can't even test it. Whenever we see a JSON string on the R side, we want to catch and rethrow in C++. Much later, we can think about JSONifying everything in https://github.com/duckdb/duckdb-r/issues/519.
