### ISSUE TITLE
how to understand how duckplyr was built?

### ISSUE THREAD

**Issue by maelle** [tidyverse/duckplyr#24]
Here is what I (think I) understand and don't understand. There'd be value in writing it up in a contributing guide for fixing current problems, onboarding collaborators, maybe even inspiring people with similar goals (as a side effect, not a priority).

- code from `tools/` was sourced in alphabetical order.
- what are the subfolders in `tools/`?
- there's something ensuring duckplyr can be synced? at least I see things related to git diff/patch?

**Comment by maelle** [comment]
Related: #25

**Comment by krlmlr** [comment]
Does `99-sync.R` work for you?

**Comment by maelle** [comment]
Taking notes for a contributing guide.

- that script assumes one has a dplyr clone in the same folder as duckplyr.

**Comment by maelle** [comment]
Then got the error

```r
Error in `mutate()`:
ℹ In argument: `test_code = pmap_chr(list(name, code, oo),
  get_test_code, .progress = TRUE)`.
Caused by error in `pmap_chr()`:
ℹ In index: 29.
Caused by error in `rel_try()` at duckplyr/R/rename_with.R:6:2:
! Fallback requested with DUCKPLYR_FORCE
Backtrace:
  1. base::source("~/Documents/cynkra/duckplyr/tools/99-sync.R", echo = TRUE)
 29. duckplyr:::rename_with.duckplyr_df(., identity)
 30. duckplyr:::rel_try(...)
       at duckplyr/R/rename_with.R:6:2
```

**Comment by maelle** [comment]
pointers would also be welcome here. :sweat_smile:

**Comment by maelle** [comment]
actually I'll retry after re-starting, in case the environment variable was set from the previous try. in that case it might make sense to use `withr`. :thinking:

**Comment by maelle** [comment]
I still get the error

```r
ℹ No relational implementation for rename_with()
Error in `mutate()`:
ℹ In argument: `test_code = pmap_chr(list(name, code, oo),
  get_test_code, .progress = TRUE)`.
Caused by error in `pmap_chr()`:
ℹ In index: 29.
Caused by error in `rel_try()` at duckplyr/R/rename_with.R:6:2:
! Fallback requested with DUCKPLYR_FORCE
Backtrace:
  1. base::source("~/Documents/cynkra/duckplyr/tools/99-sync.R", echo = TRUE)
 29. duckplyr:::rename_with.duckplyr_df(., identity)
 30. duckplyr:::rel_try(...)
       at duckplyr/R/rename_with.R:6:2
Warning message:
There were 3 warnings in `mutate()`.
The first warning was:
ℹ In argument: `decl_chr = func_decl(fun, code)`.
ℹ In row 1.
Caused by warning in `normalizePath()`:
! path[1]="": No such file or directory
ℹ Run dplyr::last_dplyr_warnings() to see the 2 remaining warnings. 
```

**Comment by maelle** [comment]
this would be a welcome addition to the contributing guide 😸

**Comment by maelle** [comment]
Dplyr clone needed in .sync/dplyr-main

**Comment by maelle** [comment]
still missing something

> > qloadm("tools/tpch/001.qs")
Error in qs::qread(file) : 
  For file tools/tpch/001.qs: Failed to open for reading. Does the file exist? Do you have file permissions? Is the file name long? (>255 chars)
