### ISSUE TITLE
Needs logo

### ISSUE THREAD

**Issue by hadley** [tidyverse/duckplyr#249]

**Comment by hannes** [comment]
Could you please take care of this @szarnyas

**Comment by szarnyasg** [comment]
Sure, the logo is available here:

* https://duckdb.org/images/logo-dl/duckplyr.png
* https://duckdb.org/images/logo-dl/duckplyr.svg

**Comment by szarnyasg** [comment]
@hadley, yes, here's the PDF used to produce the stickers: [2.17x2.5-hexagon-sticker-duckplyr.pdf](https://github.com/user-attachments/files/16692613/2.17x2.5-hexagon-sticker-duckplyr.pdf)

I will get a clean SVG version of this (without the extra lines for bleed) but I'll have to ask our designer who's not available at the moment.

A cropped PNG version of this:
![image](https://github.com/user-attachments/assets/553cdadd-af41-4ede-b771-04dc33c82d0b)

**Comment by luisDVA** [comment]
hi all,
I was making hex logos for something else and used my template to crop the high-res pdf above into the files mentioned in this [pull request](https://github.com/rstudio/hex-stickers/pull/105). If duckdblabs approves of the licensing and gives permission, those can be merged into the main hex logo repo and then added here.  
cheers

**Comment by krlmlr** [comment]
We're good on the website now, I think, except the favicon (#263).

**Comment by krlmlr** [comment]
Thanks all for your help with that!
