### ISSUE TITLE
Formatting seems broken on the website

### ISSUE THREAD

**Issue by etiennebacher** [tidyverse/duckplyr#252]
Hi, the formatting of the output of `explain()` seems broken on the website:

![image](https://github.com/user-attachments/assets/08cf6afe-e369-4e23-8ce6-c88f4e248378)

I'm using Firefox 128, but the same appears on Chrome 127, on Windows. I know the output is produced by `duckdb` upstream, but we had (maybe still have) similar issues in `r-polars` and I think it's a font issue.

**Comment by etiennebacher** [comment]
I think it's still present (also in `polars` upstream: https://github.com/pola-rs/polars/issues/11106) but in this case it only appears on Ubuntu or on mobile, so we never properly addressed it.

Here's a pending PR in upstream that might give you ideas: https://github.com/pola-rs/polars/pull/18187

**Comment by hadley** [comment]
Putting my discussion in https://github.com/pola-rs/polars/pull/18187#issuecomment-2302077398; let's close this issue so there's one less place for discussion.

**Comment by krlmlr** [comment]
Just FYI, I replaced the fancy dashes with plain dashes in ffcc1d96995b140fa3cc23c668d5ea06d8a7b82a, to be deployed to the main site (but not yet to the dev site) by https://github.com/tidyverse/duckplyr/actions/runs/10495922741. We can keep experimenting on the main branch.
