### ISSUE TITLE
No connection to duckdb file via as_duckplyr_tibble

### ISSUE THREAD

**Issue by sparrow925** [tidyverse/duckplyr#253]
Super excited to see [#266](https://github.com/tidyverse/duckplyr/pull/226), so I tried it out with v0.4.1.9003 -- encountered the following error:

```
library(tidyverse)

con = DBI::dbConnect(duckdb::duckdb(), "foo.db") #db on disk
DBI::dbWriteTable(con, name = "iris", value = iris)
dplyr::tbl(con, "iris") %>% duckplyr::as_duckplyr_tibble()
```

_Error in duckdb$rel_from_sql(con, sql) : attempt to apply non-function_

**Comment by bschneidr** [comment]
I'm really hoping we could use 'duckplyr' to connect to DuckDB files, so that it's possible to bypass the somewhat slow 'dbplyr' translation process. If I understand the ticket correctly, that's what you're trying to do here.

**Comment by krlmlr** [comment]
Thanks for the heads-up. Working on it, shouldn't be too long.

**Comment by sparrow925** [comment]
@krlmlr Fishing for an update -- Did this make it into the build?

**Comment by krlmlr** [comment]
Now:

``` r
con <- withr::local_db_connection(DBI::dbConnect(duckdb::duckdb()))

data.frame(a = 1) |>
  # Creating dbplyr frame
  dplyr::copy_to(dest = con) |>
  # Creating ducktbl
  duckplyr::as_ducktbl(.lazy = TRUE) |>
  # Running in duckplyr
  dplyr::mutate(b = 2)
#> # A duckplyr data frame: 2 variables
#>       a     b
#>   <dbl> <dbl>
#> 1     1     2
```

<sup>Created on 2024-12-16 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
