### ISSUE TITLE
Syntax highlighting in the README

### ISSUE THREAD

**Issue by etiennebacher** [tidyverse/duckplyr#254]
Minor issue but the examples in the README can be hard to read without syntax highlighting and with all the links:

![image](https://github.com/user-attachments/assets/1a6fa889-8114-4aaa-96b2-bfa190a8dbe9)

Examples of `dplyr` are much easier to read IMO:

![image](https://github.com/user-attachments/assets/9b3bbb58-18ab-4246-a4c5-eadc3f7acba3)

I think this is just a matter of replacing `output: downlit::readme_document` by `output: github_document` in README.Rmd?

**Comment by krlmlr** [comment]
Thanks, interesting. I wasn't aware that downlit kills the syntax highlighting. Need to take a closer look.

**Comment by krlmlr** [comment]
I think we're good here now, we only need to add the favicon.
