### ISSUE TITLE
ANSI escape codes are showing up in website homepage

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidyverse/duckplyr#267]
In both release and dev versions (https://duckplyr.tidyverse.org/dev/) of the website:

<img width="813" alt="Screenshot 2024-09-28 at 08 31 07" src="https://github.com/user-attachments/assets/d9274836-e2d6-4f0b-9cee-fd7174b590e6">

**Comment by krlmlr** [comment]
Thanks, good catch. Fixed for the main branch, dev branch building: https://github.com/tidyverse/duckplyr/actions/runs/11086620865 .
