### ISSUE TITLE
how to document head.duckplyr_df

### ISSUE THREAD

**Issue by maelle** [tidyverse/duckplyr#361]
not a dplyr method

**Comment by maelle** [comment]
Less sure about this one https://github.com/tidyverse/duckplyr/pull/359/commits/9e1ae47b9fda929bf577e8ea634cd66d96b91601 @krlmlr

**Comment by krlmlr** [comment]
It's good enough in https://duckplyr.tidyverse.org/dev/reference/head.duckplyr_df.html . Thanks!
