### ISSUE TITLE
Duckplyr should allow users to set s3 secret tokens etc.

### ISSUE THREAD

**Issue by Tmonster** [tidyverse/duckplyr#39]
adjacent to https://github.com/duckdblabs/duckplyr/issues/37 duckplyr does not expose any functionality to allow users to set their s3 secret keys etc. as described here. Basically users cannot execute sql against the default duckdb connection through duckplyr.

https://duckdb.org/docs/guides/import/s3_import.html

Might be nice to have functions like  `set_s3_keys(access_key, secret_access_key)`  and `set_s3_session_token(session_token)`.

We can brainstorm sometime

**Comment by krlmlr** [comment]
Would duckdb pick it up from environment variables if unset?
